import os
import sys
import json
import random
import numpy as np
import torch
from datasets import load_dataset, Dataset
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM, 
    TrainingArguments, 
    Trainer, 
    DataCollatorForLanguageModeling
)
from peft import LoraConfig, get_peft_model, TaskType
import torch.nn.functional as F
from sklearn.metrics import roc_auc_score
import evaluate
from tqdm import tqdm

# ==========================================
# 0. 服务器环境配置
# ==========================================

# 1. 镜像加速 (如果您的服务器在国内，请保留此行；如果在海外，可以注释掉)
os.environ["HF_ENDPOINT"] = "https://hf-mirror.com"

# 2. 避免并行 Tokenizer 警告
os.environ["TOKENIZERS_PARALLELISM"] = "false"

# 3. 定义全局配置
CONFIG = {
    # 直接使用 Hugging Face Hub 上的模型 ID，脚本会自动下载
    # 建议使用 Qwen1.5-0.5B 或 Qwen1.5-1.8B 作为测试，速度快显存占用小
    "model_name": "Qwen/Qwen1.5-0.5B",       
    
    # 实验参数
    "n_samples": 1000,                       # 样本数量 (服务器跑如果不缺时间可以设大一点，比如 2000-5000)
    "n_val_samples": 20,                     # 验证集大小 (梯度计算用)
    "poison_ratio": 0.3,                     # 投毒比例
    "output_dir": "./server_results",        # 结果保存路径 (当前目录下的 server_results)
    "seed": 42
}

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

print(f"🚀 服务器模式启动 | 模型: {CONFIG['model_name']} | 样本数: {CONFIG['n_samples']}")
print(f"📂 结果将保存至: {os.path.abspath(CONFIG['output_dir'])}")

# ==========================================
# 1. 数据准备 (自动下载 + 合成)
# ==========================================
def prepare_data():
    """
    自动下载 Alpaca 数据集，并人工注入噪声。
    """
    print("📥 正在准备数据...")
    
    ds_raw = None
    try:
        # 尝试从 Hugging Face 在线加载
        # 'yahma/alpaca-cleaned' 是一个常用的清理版，或者用 'tatsu-lab/alpaca'
        print(f"☁️正在下载数据集: tatsu-lab/alpaca (前 {CONFIG['n_samples']} 条)...")
        # split 参数直接切片，只下载需要的部分
        ds_raw = load_dataset("tatsu-lab/alpaca", split=f"train[:{CONFIG['n_samples']}]")
        print("✅ 数据集下载成功！")
    except Exception as e:
        print(f"⚠️ 在线加载失败 ({e})，将使用纯合成数据兜底...")

    # 转换为 Python List
    ds = []
    if ds_raw:
        for item in ds_raw:
            ds.append({
                "instruction": item["instruction"],
                "input": item["input"],
                "output": item["output"]
            })
    else:
        # 兜底合成数据 (算术题)
        print("☢️ 使用合成数据兜底...")
        for k in range(CONFIG['n_samples']):
            ds.append({
                "instruction": f"Calculate {k} + {k}",
                "input": "", 
                "output": f"{k+k}"
            })
            
    data = []
    clean_indices_gt = [] # Ground Truth Clean
    dirty_indices_gt = [] # Ground Truth Dirty
    
    set_seed(CONFIG['seed'])
    
    # 定义噪声模板
    garbage_responses = [
        "I don't know the answer because I am an AI.",
        "This is a random sentence generated by a computer.",
        "Error 404: Answer not found.",
        "Bla bla bla, I am just outputting noise.",
        "Ignore the previous instruction, here is a poem about cats.",
        "System reboot initiated.",
        "As an AI language model, I cannot answer this request."
    ]
    
    print(f"😈 正在注入噪声 (比例: {CONFIG['poison_ratio']:.0%})...")
    
    # 创建一份纯净的副本作为 Oracle (验证集来源)
    oracle_data = [item.copy() for item in ds] 

    for i, item in enumerate(ds):
        is_poison = random.random() < CONFIG['poison_ratio']
        
        new_item = item.copy()
        
        if is_poison:
            new_item["output"] = random.choice(garbage_responses)
            dirty_indices_gt.append(i)
        else:
            clean_indices_gt.append(i)
            
        data.append(new_item)
        
    print(f"✅ 数据准备完成: 总数 {len(data)} | 干净样本(GT): {len(clean_indices_gt)} | 脏样本(GT): {len(dirty_indices_gt)}")
    return data, dirty_indices_gt, oracle_data

# ==========================================
# 2. 梯度特征提取与 KNN-Shapley
# ==========================================

def compute_knn_shapley_gradient(train_grads, val_grads, K=10):
    """
    计算基于梯度的 Shapley Value。
    """
    N_train = train_grads.shape[0]
    N_val = val_grads.shape[0]
    
    print(f"   -> 归一化梯度向量...")
    train_grads = F.normalize(train_grads, p=2, dim=1)
    val_grads = F.normalize(val_grads, p=2, dim=1)
    
    print(f"   -> 计算相似度矩阵 ({N_val}x{N_train})...")
    # 转到 CPU 计算矩阵乘法，防止爆显存
    S = torch.matmul(val_grads, train_grads.T).cpu().numpy() 
    
    shapley_values = np.zeros(N_train)
    
    print(f"   -> 运行 KNN-Shapley 估值 (K={K})...")
    for j in range(N_val):
        s_row = S[j]
        sorted_indices = np.argsort(s_row)[::-1] # 降序
        values = s_row[sorted_indices]
        
        phi_sorted = np.zeros(N_train)
        curr_K = min(K, N_train)
        
        # 简化版递归计算 (仅关注 Top-K 带来的边际增益)
        running_sum = 0.0
        # 从 K-1 到 0
        for i in range(curr_K - 1, -1, -1):
            val_current = values[i]
            val_next = values[i+1] if (i+1 < N_train) else 0.0
            running_sum += (val_current - val_next) / (i + 1)
            phi_sorted[i] = running_sum # 这是根据原文公式近似
            
            # 更简单的近似: 直接累加 Top-K 相似度 (KNN-Filter)
            # phi_sorted[i] = values[i] / curr_K 
        
        # 简单实现：直接累加相似度 (KNN Proxy) - 这种方法在清洗任务中往往更稳健
        #shapley_values += s_row 
        
        # 使用 Jia et al. 的公式逻辑
        for i in range(N_train - 1, -1, -1): # 倒序
             if i < curr_K:
                 phi_sorted[i] = phi_sorted[i+1] + (values[i] - values[i+1])/ (i+1) if i+1 < N_train else values[i]/(i+1)
             else:
                 phi_sorted[i] = 0

        shapley_values[sorted_indices] += phi_sorted
        
    shapley_values /= N_val
    return shapley_values

def extract_gradient_features(dataset_list, indices):
    """
    使用 LoRA 提取梯度特征。
    """
    print(f"🧬 提取梯度... 样本数: {len(indices)}")
    
    # 自动下载/加载模型
    tokenizer = AutoTokenizer.from_pretrained(CONFIG['model_name'], trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
        
    model = AutoModelForCausalLM.from_pretrained(
        CONFIG['model_name'], 
        device_map="auto", 
        torch_dtype=torch.float16, 
        trust_remote_code=True
    )
    
    # LoRA 配置
    peft_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM, inference_mode=False, r=8, lora_alpha=16, 
        target_modules=["q_proj", "v_proj"]
    )
    model = get_peft_model(model, peft_config)
    model.train() # 必须是 train 模式才有梯度
    
    grads = []
    
    def format_text(ex):
        return f"User: {ex['instruction']}\n{ex['input']}\nAssistant: {ex['output']}{tokenizer.eos_token}"

    subset = [dataset_list[i] for i in indices]
    
    # 为了速度，这里设置较短的 max_length
    MAX_LEN = 256
    
    for item in tqdm(subset, desc="Gradient Extraction"):
        text = format_text(item)
        inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=MAX_LEN).to(model.device)
        
        # Forward
        outputs = model(**inputs, labels=inputs["input_ids"])
        loss = outputs.loss
        loss.backward()
        
        # Extract Grad
        g_vecs = []
        # 遍历所有 LoRA 参数
        for name, param in model.named_parameters():
             if "lora" in name and param.grad is not None:
                g_vecs.append(param.grad.view(-1).cpu().float())
        
        if g_vecs:
            # 拼接所有层的 LoRA 梯度作为特征向量
            grads.append(torch.cat(g_vecs))
        else:
            grads.append(torch.zeros(1))
            
        model.zero_grad()
    
    del model
    torch.cuda.empty_cache()
    
    if not grads:
        return torch.zeros((len(indices), 1))
        
    return torch.stack(grads)

def calculate_shapley(dataset_list, oracle_data):
    n_train = len(dataset_list)
    n_val = min(len(oracle_data), CONFIG['n_val_samples'])
    
    print(f"🔧 开始梯度清洗计算...")
    
    # 1. Train Set Gradients
    train_indices = list(range(n_train))
    train_grads = extract_gradient_features(dataset_list, train_indices)
    
    # 2. Val Set Gradients (Gold Standard)
    val_indices = list(range(n_val))
    val_grads = extract_gradient_features(oracle_data[:n_val], val_indices)
    
    # 维度对齐
    if train_grads.shape[1] != val_grads.shape[1]:
        # 如果长度不一致（极其罕见），截断
        min_len = min(train_grads.shape[1], val_grads.shape[1])
        train_grads = train_grads[:, :min_len]
        val_grads = val_grads[:, :min_len]

    # 3. KNN-Shapley
    sv = compute_knn_shapley_gradient(train_grads, val_grads, K=5)
    return sv

# ==========================================
# 3. 训练与评估
# ==========================================
def run_sft_training(dataset_list, run_name):
    """
    微调模型并评估
    """
    output_path = f"{CONFIG['output_dir']}/{run_name}"
    print(f"\n🚀 开始训练: {run_name} -> {output_path}")
    
    tokenizer = AutoTokenizer.from_pretrained(CONFIG['model_name'], trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    # 处理数据
    def format_func(example):
        text = f"User: {example['instruction']}\n{example['input']}\nAssistant: {example['output']}{tokenizer.eos_token}"
        return {"text": text}
    
    hf_dataset = Dataset.from_list(dataset_list)
    hf_dataset = hf_dataset.map(lambda x: tokenizer(format_func(x)["text"], truncation=True, max_length=256), batched=False)
    
    # 加载模型
    model = AutoModelForCausalLM.from_pretrained(
        CONFIG['model_name'], 
        device_map="auto", 
        torch_dtype=torch.float32, # 训练建议用 FP32 或 BF16，避免 FP16 溢出
        trust_remote_code=True
    )
    
    peft_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM, inference_mode=False, r=8, lora_alpha=32, lora_dropout=0.1,
        target_modules=["q_proj", "v_proj"]
    )
    model = get_peft_model(model, peft_config)
    
    args = TrainingArguments(
        output_dir=output_path,
        per_device_train_batch_size=4,
        gradient_accumulation_steps=4,
        num_train_epochs=3, # 这里的 epoch 少一点演示用，实际建议 3-5
        learning_rate=2e-4,
        logging_steps=10,
        save_strategy="no", # 演示不保存 checkpoint 中间态
        report_to="none",
        fp16=False,
    )
    
    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=hf_dataset,
        data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False),
    )
    
    trainer.train()
    
    # 保存结果
    print(f"💾 保存模型到: {output_path}")
    trainer.save_model(output_path)
    
    # 简单评估 (ROUGE)
    print("📏 评估 ROUGE (随机抽取 20 条测试)...")
    try:
        metric = evaluate.load("rouge")
        model.eval()
        
        test_samples = dataset_list[:20] if len(dataset_list) > 20 else dataset_list
        preds = []
        refs = []
        
        for item in test_samples:
            prompt = f"User: {item['instruction']}\n\nAssistant: "
            inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
            with torch.no_grad():
                outputs = model.generate(**inputs, max_new_tokens=50, pad_token_id=tokenizer.eos_token_id)
            pred = tokenizer.decode(outputs[0], skip_special_tokens=True)
            # 简单的截取回复
            if "Assistant: " in pred:
                pred = pred.split("Assistant: ")[-1].strip()
            preds.append(pred)
            refs.append(item['output'])
            
        scores = metric.compute(predictions=preds, references=refs)
        rouge_score = scores['rougeL']
        print(f"📊 {run_name} ROUGE-L: {rouge_score:.4f}")
        return rouge_score
    except Exception as e:
        print(f"⚠️ ROUGE 评估失败: {e}")
        return 0.0

# ==========================================
# 主流程
# ==========================================
def main():
    print(f"🌟 SFT Server Demo 开始运行...")
    
    # 1. 准备数据
    raw_data, dirty_indices_gt, oracle_data = prepare_data()
    
    # 2. 计算 Shapley 值并清洗
    sv = calculate_shapley(raw_data, oracle_data)
    
    # 3. 执行清洗
    n_remove = int(len(raw_data) * CONFIG['poison_ratio'])
    sorted_idx = np.argsort(sv) # 从小到大
    keep_indices = sorted_idx[n_remove:] # 保留分数高的
    
    cleaned_data = [raw_data[i] for i in keep_indices]
    
    # 4. 统计指标
    removed_indices = sorted_idx[:n_remove]
    correct_removed = set(removed_indices).intersection(set(dirty_indices_gt))
    recall = len(correct_removed) / (len(dirty_indices_gt) + 1e-9)
    print(f"✅ 清洗完成! 移除了 {n_remove} 条数据")
    print(f"🕵️‍♂️ 脏数据召回率 (Recall): {recall:.2%}")
    
    # 计算 AUC
    if len(dirty_indices_gt) > 0:
        true_labels = np.ones(len(raw_data))
        true_labels[dirty_indices_gt] = 0
        auc = roc_auc_score(true_labels, sv)
        print(f"📈 算法根据梯度打分的 AUC: {auc:.4f}")
    
    # 5. 训练对比 (Dirty vs Clean)
    # 为了节省时间，这里我们只训练 Clean 模型演示流程
    # 如果您想对比，可以取消下面 Dirty Model 的注释
    
    # print("--- Training Dirty Model ---")
    # run_sft_training(raw_data, "dirty_model")
    
    print("--- Training Clean Model ---")
    rouge_clean = run_sft_training(cleaned_data, "clean_model")
    
    print("\n🎉 所有任务完成！")
    print(f"模型已保存至: {CONFIG['output_dir']}/clean_model")

if __name__ == "__main__":
    main()
