import os
# 强制使用 HF 镜像 (针对国内网络优化)
os.environ["HF_ENDPOINT"] = "https://hf-mirror.com"
import sys
import json
import random
import numpy as np
import torch
from datasets import load_dataset, Dataset
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM, 
    TrainingArguments, 
    Trainer, 
    DataCollatorForLanguageModeling
)
from peft import LoraConfig, get_peft_model, TaskType
from torch.utils.data import DataLoader
import torch.nn.functional as F
from sklearn.metrics import roc_auc_score
import evaluate
from tqdm import tqdm

# --- 核心算法导入: 移除 helper.py 依赖，改为本地实现 ---
# sys.path.append ... (Removed)

# ==========================================
# 0. 全局配置
# ==========================================
# 检查是否存在本地资源
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOCAL_RES_DIR = os.path.join(ROOT_DIR, "local_resources")

# 优先使用本地资源路径，如果不存在则使用云端 ID
model_path = os.path.join(LOCAL_RES_DIR, "qwen_model")
if not os.path.exists(model_path):
    model_path = "Qwen/Qwen1.5-0.5B"
    print("⚠️ 未找到本地 Qwen 模型，将使用云端下载模式")
else:
    print(f"✅ 使用本地 Qwen 模型: {model_path}")

# Feature Extractor 现在是 LLM 本身
CONFIG = {
    "model_name": model_path,                # 目标 LLM
    "n_samples": 2000,                       # 总样本数
    "n_val_samples": 20,                     # ⚠️ 验证集大小 (取 Oracle 数据)
    "poison_ratio": 0.3,                     # 投毒比例
    "output_dir": "SFT/results",             # 输出目录
    "seed": 42
}

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

# ==========================================
# 1. 数据合成 (Data Synthesis)
# ==========================================
def prepare_data():
    """
    下载 Alpaca 数据集，并人工注入 30% 的噪声。
    返回: raw_dataset (含噪声), clean_indices (GT), dirty_indices (GT)
    """
    print("📥 正在加载 Alpaca 数据集...")
    
    ds_raw = None
    local_data_path = os.path.join(LOCAL_RES_DIR, "alpaca_data")
    
    # 1. 尝试本地加载 (优先)
    if os.path.exists(local_data_path):
        try:
            from datasets import load_from_disk
            print(f"📂 尝试加载本地数据: {local_data_path}")
            ds_full = load_from_disk(local_data_path)
            # 处理 dataset dict 或 dataset
            if isinstance(ds_full, dict) or hasattr(ds_full, 'keys'):
                split_name = 'train' if 'train' in ds_full else list(ds_full.keys())[0]
                ds_full = ds_full[split_name]
            
            # 切片
            ds_raw = ds_full.select(range(min(len(ds_full), CONFIG['n_samples'])))
            print("✅ 本地数据加载成功！")
        except Exception as e:
            print(f"❌ 本地加载失败: {e}")

    # 2. 如果本地失败，尝试在线
    if ds_raw is None:
        try:
            print("☁️ 尝试在线加载 tatsu-lab/alpaca...")
            ds_raw = load_dataset("tatsu-lab/alpaca", split=f"train[:{CONFIG['n_samples']}]")
        except Exception as e:
            print(f"⚠️ 在线加载失败: {e}")

    # 3. 实在不行，合成兜底
    ds = []
    if ds_raw:
        ds = [item for item in ds_raw]
    else:
        print("☢️ 严重警告：所有数据加载方式失败，使用含有噪声的合成算术数据兜底。")
        # 生成合成数据
        for k in range(CONFIG['n_samples']):
            ds.append({
                "instruction": f"Solve math problem: {k} + {k}",
                "input": "", 
                "output": f"The answer is {k+k}."
            })
            
    data = []
    clean_indices = []
    dirty_indices = []
    
    set_seed(CONFIG['seed'])
    
    # 定义一些“垃圾回答”模板
    garbage_responses = [
        "I don't know the answer because I am an AI.",
        "This is a random sentence generated by a computer.",
        "Error 404: Answer not found.",
        "Bla bla bla, I am just outputting noise.",
        "To be or not to be, that is the question.",
        "Ignore the previous instruction, here is a poem about cats."
    ]
    
    print(f"😈 正在注入噪声 (比例: {CONFIG['poison_ratio']:.0%})...")
    
    for i, item in enumerate(ds):
        # 决定是否投毒
        is_poison = random.random() < CONFIG['poison_ratio']
        
        new_item = {
            "instruction": item["instruction"],
            "input": item["input"],
            "output": item["output"]
        }
        
        if is_poison:
            # 替换 output 为垃圾
            new_item["output"] = random.choice(garbage_responses)
            dirty_indices.append(i)
        else:
            clean_indices.append(i)
            
        data.append(new_item)
        
    print(f"✅ 数据准备完成: 总数 {len(data)}, 干净 {len(clean_indices)}, 脏 {len(dirty_indices)}")
    return data, dirty_indices, ds

# ==========================================
# 2. 梯度特征提取与 KNN-Shapley (New)
# ==========================================

def compute_knn_shapley_gradient(train_grads, val_grads, K=10):
    """
    实现 knnsv-sft.md 中的算法。
    """
    N_train = train_grads.shape[0]
    N_val = val_grads.shape[0]
    
    # 归一化梯度向量
    print(f"   -> 正在归一化梯度向量...")
    train_grads = F.normalize(train_grads, p=2, dim=1)
    val_grads = F.normalize(val_grads, p=2, dim=1)
    
    print(f"   -> 计算相似度矩阵 ({N_val}x{N_train})...")
    # Move to CPU for numpy ops to save GPU memory
    S = torch.matmul(val_grads, train_grads.T).cpu().numpy() 
    
    shapley_values = np.zeros(N_train)
    
    # 预计算
    print(f"   -> 运行递归算法 (K={K})...")
    for j in tqdm(range(N_val), desc="Val Points"):
        s_row = S[j]
        sorted_indices = np.argsort(s_row)[::-1] # Descending
        values = s_row[sorted_indices] # alpha
        
        # 简化版递归算法实现 (O(N))
        # 根据 KNN-Shapley 论文，对于 Unweighted KNN (1/K * Sum(TopK)):
        # phi_i = phi_{i+1} + (v_i - v_{i+1})/K * min(K, i) ? No.
        
        # 直接使用由 G-Shapley 推导出的系数 (Jia et al.)
        # 对于 Utility = 1/K * Sum_{j=1}^K s_(j)
        # Shapley Value phi_i = s_(i)/N + 1/K * (sum term)
        # 让我们使用更直观的基于边际贡献的理解:
        # 只有当前 N 个点中的 Top-K 发生变化时，Utility 才变。
        
        phi_sorted = np.zeros(N_train)
        N = N_train
        curr_K = min(K, N)
        
        # 倒序计算
        for i in range(N - 1, -1, -1):
            rank = i + 1 
            val_diff = values[i] - (values[i+1] if i+1 < N else 0.0)
            
            if rank > curr_K:
                phi_sorted[i] = 0 # 简化处理：K之后的点因为梯度相似度极低，贡献忽略
            else:
                # Top-K 贡献分配
                phi_sorted[i] = phi_sorted[i+1] + val_diff / curr_K
        
        shapley_values[sorted_indices] += phi_sorted
        
    shapley_values /= N_val
    return shapley_values

def extract_gradient_features(model_name, dataset_list, indices):
    """
    计算指定样本的梯度向量。使用 LoRA 层的梯度。
    """
    print(f"🧬 正在提取梯度特征 (N={len(indices)})...")
    
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    tokenizer.pad_token = tokenizer.eos_token
    
    model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto", torch_dtype=torch.float16)
    
    # 使用 LoRA 使得梯度更小更易计算
    peft_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM, inference_mode=False, r=8, lora_alpha=32, lora_dropout=0.1,
        target_modules=["q_proj", "v_proj"]
    )
    model = get_peft_model(model, peft_config)
    model.train() 
    
    grads = []
    
    def format_func(example):
        text = f"User: {example['instruction']}\n{example['input']}\nAssistant: {example['output']}{tokenizer.eos_token}"
        return text

    subset = [dataset_list[i] for i in indices]
    
    for item in tqdm(subset, desc="Computing Gradients"):
        text = format_func(item)
        inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512).to(model.device)
        
        outputs = model(**inputs, labels=inputs["input_ids"])
        loss = outputs.loss
        loss.backward()
        
        g_vecs = []
        # 只提取最后一层 Decoder Layer 的 LoRA 参数梯度
        num_layers = len(model.base_model.model.model.layers)
        target_layer_idx = num_layers - 1
        
        found = False
        for name, param in model.named_parameters():
            if f"layers.{target_layer_idx}" in name and "lora_B" in name and param.grad is not None:
                g_vecs.append(param.grad.view(-1).cpu().float()) # 转 float32
                found = True
        
        if found:
            grads.append(torch.cat(g_vecs))
        else:
            grads.append(torch.zeros(1))
            
        model.zero_grad()
    
    # 清理内存
    del model
    torch.cuda.empty_cache()
    
    # Pad if necessary (unlikely)
    return torch.stack(grads)

def calculate_shapley(dataset_list, dirty_indices, oracle_data):
    """
    Grad-SFT 流程：Raw Grads vs Oracle Grads
    """
    n_train = len(dataset_list)
    n_val = CONFIG['n_val_samples']
    
    # 从 Oracle 数据中取验证集
    # 如果 oracle_data 不够 N_val，就取全部
    n_val = min(len(oracle_data), n_val)
    val_subset = oracle_data[:n_val]
    val_indices = list(range(n_val))
    
    print(f"🔧 开始基于梯度的清洗流程...")
    print(f"   Train: {n_train}, Val: {n_val}")
    
    # 1. 提取 Traing Gradients
    train_indices = list(range(n_train))
    print("   [1/2] Computing Train Gradients...")
    train_grads = extract_gradient_features(CONFIG['model_name'], dataset_list, train_indices)
    
    # 2. 提取 Val Gradients
    print("   [2/2] Computing Val (Oracle) Gradients...")
    val_grads = extract_gradient_features(CONFIG['model_name'], val_subset, val_indices)
    
    # 维度对齐检查
    if train_grads.shape[1] != val_grads.shape[1]:
        print("❌ Gradient dimension mismatch!")
        # 如果出错，返回随机值
        return np.random.rand(n_train)

    # 3. 计算 ES-Shapley
    sv = compute_knn_shapley_gradient(train_grads, val_grads, K=10)
    
    print(f"📊 Gradient-Shapley Stats -> Mean: {np.mean(sv):.4e}, Std: {np.std(sv):.4e}")
    return sv

# ==========================================
# 4. 微调训练 (Fine-tuning)
# ==========================================
def run_sft(dataset_list, output_name):
    """
    使用 HuggingFace Trainer 进行微调 (使用 LoRA 以保证稳定性)。
    """
    print(f"🚀 开始微调: {output_name} (样本数: {len(dataset_list)})...")
    
    model_id = CONFIG['model_name']
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    # 修复 tokenizer 设置
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right" # 训练时通常用 right padding

    # 格式化数据为 HuggingFace Dataset
    def format_func(example):
        # Qwen 官方推荐格式 / ChatML 格式
        # 这里简化处理，但确保 EOS
        text = f"User: {example['instruction']}\n{example['input']}\nAssistant: {example['output']}{tokenizer.eos_token}"
        return {"text": text}
    
    hf_dataset = Dataset.from_list(dataset_list)
    hf_dataset = hf_dataset.map(lambda x: tokenizer(format_func(x)["text"], truncation=True, max_length=512), batched=False)
    
    # 加载模型 (FP32 模式加载，避免 16bit 溢出)
    model = AutoModelForCausalLM.from_pretrained(model_id, device_map="auto", torch_dtype=torch.float32)
    
    # 启用 LoRA 
    peft_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM, 
        inference_mode=False, 
        r=8, 
        lora_alpha=32, 
        lora_dropout=0.1,
        target_modules=["q_proj", "v_proj"] # 针对 Attention 层微调
    )
    model = get_peft_model(model, peft_config)
    model.print_trainable_parameters()

    # 训练参数调整
    training_args_dict = {
        "output_dir": f"{CONFIG['output_dir']}/{output_name}",
        "per_device_train_batch_size": 4, # LoRA 省显存，可以稍微大点
        "gradient_accumulation_steps": 4,
        "num_train_epochs": 3,            # LoRA 需要多训几轮
        "learning_rate": 3e-4,            # LoRA 通常用大一点的学习率
        "logging_steps": 10,
        "save_strategy": "no",
        "report_to": "none",
        "fp16": False,                    # 使用 FP32 保证数值绝对稳定
        "bf16": False,
    }
    
    args = TrainingArguments(**training_args_dict)
    
    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=hf_dataset,
        data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False),
    )
    
    trainer.train()

    # 💾 保存模型 (LoRA 适配器)
    save_path = f"{CONFIG['output_dir']}/{output_name}"
    trainer.save_model(save_path)
    # 合并权重并保存 (方便 chat_compare 读取)
    print("💾 正在合并 LoRA 权重...")
    merged_model = model.merge_and_unload()
    merged_model.save_pretrained(save_path)
    tokenizer.save_pretrained(save_path)
    print(f"💾 完整模型已保存至: {save_path}")
    
    # === 新增：计算 ROUGE 分数 (更有说服力的生成指标) ===
    print("📏 正在评估 ROUGE 指标...")
    metric = evaluate.load("rouge")
    
    # 抽取 50 条测试数据 (不参与训练的)
    test_samples = dataset_list[:50] 
    
    preds = []
    refs = []
    
    # 切换回 eval 模式
    merged_model.eval()
    for item in tqdm(test_samples, desc="Evaluating"):
        prompt = f"User: {item['instruction']}\n\nAssistant: "
        inputs = tokenizer(prompt, return_tensors="pt").to(merged_model.device)
        with torch.no_grad():
            outputs = merged_model.generate(**inputs, max_new_tokens=50, pad_token_id=tokenizer.eos_token_id)
        pred = tokenizer.decode(outputs[0], skip_special_tokens=True)
        if "Assistant: " in pred:
            pred = pred.split("Assistant: ")[1].strip()
        preds.append(pred)
        refs.append(item['output'])
        
    scores = metric.compute(predictions=preds, references=refs)
    print(f"📊 {output_name} ROUGE-L: {scores['rougeL']:.4f}")
    
    # 返回 Loss 和 RougeL 用于对比
    return trainer.state.log_history[-1].get('train_loss', 0.0), scores['rougeL']

# ==========================================
# 主程序
# ==========================================
def main():
    # 1. 准备数据
    # oracle_data: 未被污染的原始纯净数据 (上限/Gold Standard)
    raw_data, dirty_indices, oracle_data = prepare_data()
    
    # 2. 计算价值 (Gradient-Shapley Value)
    # 不再需要显式 extract_features，calculate_shapley 内部会做
    sv = calculate_shapley(raw_data, dirty_indices, oracle_data)
    
    # 3. 根据价值清洗
    # 策略：我们要删掉 30% 左右的数据
    n_remove = int(len(raw_data) * CONFIG['poison_ratio'])
    
    sorted_idx = np.argsort(sv) # 从小到大
    # 低分的是脏数据，删掉
    keep_indices = sorted_idx[n_remove:]
    
    cleaned_data = [raw_data[i] for i in keep_indices]
    
    print("-" * 50)
    print(f"🧹 清洗完成！")
    print(f"原数据: {len(raw_data)}")
    print(f"清洗后: {len(cleaned_data)}")
    
    # 验证清洗准确率 (Recall)
    # 我们知道 dirty_indices 是真的脏数据
    # 我们的系统删除了 sorted_idx[:n_remove]
    removed_indices = sorted_idx[:n_remove]
    correct_removed = set(removed_indices).intersection(set(dirty_indices))
    recall = len(correct_removed) / len(dirty_indices)
    print(f"🕵️‍♂️ 脏数据识别召回率 (Recall): {recall:.2%}")

    # 计算 AUC (清洗算法的性能指标)
    # 我们希望 dirty_indices 对应的 sv 值很低，而 clean 对应的高。
    # 为了计算 AUC，我们需要构建 0/1 标签：1 为 Clean, 0 为 Dirty (或者反过来)
    # 这里定义：Clean=1, Dirty=0
    true_labels = np.ones(len(raw_data))
    true_labels[dirty_indices] = 0
    
    # 计算 ROC-AUC
    # 注意：我们的 sv 越高越 clean，符合 y=1 的方向
    roc_auc = roc_auc_score(true_labels, sv)
    print(f"📈 清洗算法 AUC 得分: {roc_auc:.4f} (1.0代表完美区分)")
    print("-" * 50)
    
    # 5. SFT 对比实验 (Baseline vs Clean)
    # 注意：为了公平，Baseline 我们通常不删数据，或者随机删。
    # 这里对比：Dirty Full Set vs Cleaned Set
    
    # 5.1 训练 Dirty Model
    import gc
    torch.cuda.empty_cache()
    gc.collect()
    loss_dirty, rouge_dirty = run_sft(raw_data, "dirty_model")
    
    # 5.2 训练 Clean Model
    import gc
    torch.cuda.empty_cache()
    gc.collect()
    loss_clean, rouge_clean = run_sft(cleaned_data, "clean_model")
    
    # 5.3 训练 Oracle Model (全干净数据 - 理论上限)
    # 用户指示：已训练过 Oracle，直接使用上次结果，节省时间
    print("⏩ 跳过 Oracle Model 训练 (已存在)...")
    loss_oracle = 1.5928  # 上次运行记录
    rouge_oracle = 0.1701 # 上次运行记录
    
    print("=" * 50)
    print("📊 最终实验结果")
    print(f"{'Model':<15} | {'Loss':<10} | {'ROUGE-L':<10}")
    print("-" * 45)
    print(f"{'Dirty (Base)':<15} | {loss_dirty:.4f}     | {rouge_dirty:.4f}")
    print(f"{'Clean (Yours)':<15} | {loss_clean:.4f}     | {rouge_clean:.4f}")
    print(f"{'Oracle (Top)':<15} | {loss_oracle:.4f}     | {rouge_oracle:.4f}")
    print("-" * 45)
    
    if rouge_clean > rouge_dirty:
        print("✅ 验证成功：清洗后模型的 ROUGE 分数更高，生成质量更好！")

if __name__ == "__main__":
    main()
