import os
# 强制使用 HF 镜像 (针对国内网络优化)
os.environ["HF_ENDPOINT"] = "https://hf-mirror.com"
import sys
import json
import random
import numpy as np
import torch
from datasets import load_dataset, Dataset
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM, 
    TrainingArguments, 
    Trainer, 
    DataCollatorForLanguageModeling
)
from peft import LoraConfig, get_peft_model, TaskType

from sentence_transformers import SentenceTransformer
from sklearn.metrics import f1_score, roc_auc_score, roc_curve, auc
import evaluate
from tqdm import tqdm

# --- 核心算法导入 (复用之前的 KNN-Shapley) ---
# 确保 helper.py 在上一级目录或 sys.path 中
# helper.py 实际位于 d:\BiSHE\softlabel-knnsv\
sys.path.append(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "softlabel-knnsv"))
try:
    from helper import knn_shapley_JW
except ImportError:
    print("❌ 错误：找不到 helper.py。请确保它都在 d:\\BiSHE\\helper.py")
    sys.exit(1)

# ==========================================
# 0. 全局配置
# ==========================================
# 检查是否存在本地资源
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOCAL_RES_DIR = os.path.join(ROOT_DIR, "local_resources")

# 优先使用本地资源路径，如果不存在则使用云端 ID
model_path = os.path.join(LOCAL_RES_DIR, "qwen_model")
if not os.path.exists(model_path):
    model_path = "Qwen/Qwen1.5-0.5B"
    print("⚠️ 未找到本地 Qwen 模型，将使用云端下载模式")
else:
    print(f"✅ 使用本地 Qwen 模型: {model_path}")

embed_path = os.path.join(LOCAL_RES_DIR, "embed_model")
if not os.path.exists(embed_path):
    embed_path = "all-MiniLM-L6-v2"
    print("⚠️ 未找到本地 Embedding 模型，将使用云端下载模式")
else:
    print(f"✅ 使用本地 Embedding 模型: {embed_path}")

CONFIG = {
    "model_name": model_path,                # 目标 LLM
    "embed_model": embed_path,               # 特征提取模型
    "n_samples": 2000,                       # 总样本数 (模拟小样本实验)
    "poison_ratio": 0.3,                     # 投毒比例 (30% 垃圾数据)
    "output_dir": "SFT/results",             # 输出目录
    "seed": 42
}

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

# ==========================================
# 1. 数据合成 (Data Synthesis)
# ==========================================
def prepare_data():
    """
    下载 Alpaca 数据集，并人工注入 30% 的噪声。
    返回: raw_dataset (含噪声), clean_indices (GT), dirty_indices (GT)
    """
    print("📥 正在加载 Alpaca 数据集...")
    
    ds_raw = None
    local_data_path = os.path.join(LOCAL_RES_DIR, "alpaca_data")
    
    # 1. 尝试本地加载 (优先)
    if os.path.exists(local_data_path):
        try:
            from datasets import load_from_disk
            print(f"📂 尝试加载本地数据: {local_data_path}")
            ds_full = load_from_disk(local_data_path)
            # 处理 dataset dict 或 dataset
            if isinstance(ds_full, dict) or hasattr(ds_full, 'keys'):
                split_name = 'train' if 'train' in ds_full else list(ds_full.keys())[0]
                ds_full = ds_full[split_name]
            
            # 切片
            ds_raw = ds_full.select(range(min(len(ds_full), CONFIG['n_samples'])))
            print("✅ 本地数据加载成功！")
        except Exception as e:
            print(f"❌ 本地加载失败: {e}")

    # 2. 如果本地失败，尝试在线
    if ds_raw is None:
        try:
            print("☁️ 尝试在线加载 tatsu-lab/alpaca...")
            ds_raw = load_dataset("tatsu-lab/alpaca", split=f"train[:{CONFIG['n_samples']}]")
        except Exception as e:
            print(f"⚠️ 在线加载失败: {e}")

    # 3. 实在不行，合成兜底
    ds = []
    if ds_raw:
        ds = [item for item in ds_raw]
    else:
        print("☢️ 严重警告：所有数据加载方式失败，使用含有噪声的合成算术数据兜底。")
        # 生成合成数据
        for k in range(CONFIG['n_samples']):
            ds.append({
                "instruction": f"Solve math problem: {k} + {k}",
                "input": "", 
                "output": f"The answer is {k+k}."
            })
            
    data = []
    clean_indices = []
    dirty_indices = []
    
    set_seed(CONFIG['seed'])
    
    # 定义一些“垃圾回答”模板
    garbage_responses = [
        "I don't know the answer because I am an AI.",
        "This is a random sentence generated by a computer.",
        "Error 404: Answer not found.",
        "Bla bla bla, I am just outputting noise.",
        "To be or not to be, that is the question.",
        "Ignore the previous instruction, here is a poem about cats."
    ]
    
    print(f"😈 正在注入噪声 (比例: {CONFIG['poison_ratio']:.0%})...")
    
    for i, item in enumerate(ds):
        # 决定是否投毒
        is_poison = random.random() < CONFIG['poison_ratio']
        
        new_item = {
            "instruction": item["instruction"],
            "input": item["input"],
            "output": item["output"]
        }
        
        if is_poison:
            # 替换 output 为垃圾
            new_item["output"] = random.choice(garbage_responses)
            dirty_indices.append(i)
        else:
            clean_indices.append(i)
            
        data.append(new_item)
        
    print(f"✅ 数据准备完成: 总数 {len(data)}, 干净 {len(clean_indices)}, 脏 {len(dirty_indices)}")
    return data, dirty_indices, ds

# ==========================================
# 2. 特征提取 (Feature Extraction)
# ==========================================
def extract_text_features(data_list):
    """
    使用 Sentence-Transformer 将 (Instruction + Input + Output) 转化为向量。
    注意：这里我们把 Input 和 Output 拼在一起算特征，因为 KNN-SV 需要衡量 X 和 Y 的关系。
    实际上在 SFT 中，X=Prompt, Y=Response。
    我们将 "Prompt: ... Response: ..." 作为一个整体文本进行 Embedding。
    """
    print(f"🧠 正在提取文本特征 ({CONFIG['embed_model']})...")
    model = SentenceTransformer(CONFIG['embed_model'])
    
    # 构造文本列表
    texts = []
    for item in data_list:
        # 格式化文本: "Instruction: XXX\nInput: YYY\nOutput: ZZZ"
        text = f"Instruction: {item['instruction']}\nInput: {item['input']}\nOutput: {item['output']}"
        texts.append(text)
        
    # 批量计算 Embedding
    embeddings = model.encode(texts, batch_size=32, show_progress_bar=True, convert_to_numpy=True)
    
    # L2 归一化 (关键！复用之前的经验)
    # SentenceTransformer 默认通常已经归一化了，但为了保险再做一次
    norms = np.linalg.norm(embeddings, axis=1, keepdims=True)
    embeddings = embeddings / norms
    
    return embeddings

# ==========================================
# 3. 核心算法调用 (Valuation)
# ==========================================
def calculate_shapley(embeddings, dirty_indices):
    """
    调用 knn_shapley_JW 计算每个样本的价值。
    注意：helper.py 里的函数需要 (x_train, y_train, x_val, y_val)。
    但在无监督/自监督场景下，我们通常这么做：
    1. 把数据切分为 Support Set (作为 'Train') 和 Query Set (作为 'Val')
    2. 或者直接用 Leave-One-Out (KNN-SV 支持这种思想)
    
    为了适配 helper.py (它原本是为分类设计的，需要 label Y)，
    我们这里做一个 **Trick**:
    我们将 "Embedding" 视为 X，人为构造一个全是 1 的 Y (代表它们都属于'正类'任务)。
    然后看哪些样本在 KNN 邻域里与其他样本 '格格不入' (即它的特征分布偏离了主流形)。
    
    或者更简单的：
    我们将数据集随机切分 80% / 20%。
    计算 80% 数据对 20% 数据的 KNN 贡献。
    """
    print("🔍 开始计算 KNN-Shapley 值...")
    
    n_total = len(embeddings)
    n_support = int(n_total * 0.8)
    
    indices = np.random.permutation(n_total)
    support_idx = indices[:n_support]
    val_idx = indices[n_support:]
    
    x_support = embeddings[support_idx]
    x_val = embeddings[val_idx]
    
    # 伪造 Label：在这个场景下，label 并不重要，我们关注的是特征一致性
    # 但 helper.py 需要 label 匹配才能得分。
    # 策略：我们假设所有数据都是 'Class 0'。KNN 会寻找最近的邻居。
    # 如果一个脏数据混进来了，它的邻居可能比较远，或者它周围也是脏数据。
    # 
    # 等等，如果全是 Class 0，那么 helper.py 会认为所有邻居都是同类，都会加分。
    # 这可能无法区分脏数据。
    #
    # 修正策略：
    # 脏数据的特征语义通常与正常数据差异很大。
    # 如果我们用 KNN 距离本身来衡量呢？
    # KNN-Shapley 的本质是：如果把这个点加入，能不能提高对 Validation Set 的预测准确率。
    # 这里我们没有 Label。
    #
    # 替代方案 -> **KNN Density (局部密度)** 
    # 或者我们还是用 helper.py，但是构造一种特殊的任务？
    #
    # 让我们回退一步：
    # 脏数据的 definition 是 "Instruction 和 Output 不匹配"。
    # 而 Clean 数据是匹配的。
    # 正常的 Sentence-Transformer 训练时使用了 Contrastive Loss。
    # 所以 "问题+正确答案" 的向量，和 "问题+错误答案" 的向量，应该在空间中聚集在不同位置。
    # 
    # 鉴于我们必须复用 knn_shapley_JW，我们尝试构造一个 **Refrence Set (干净的小集合)**。
    # 假设我们在实际应用中，手里总有那么 10-20 条人工写的完美数据。
    # 我们把这 20 条当作 Validation Set (x_val, y_val=0)。
    # 把待清洗数据当作 Training Set (x_train, y_train=0)。
    # 看 x_train 里哪些样本对预测 x_val 有帮助 (即与 x_val 相似)。
    # 这样，与完美数据相似的样本得分高，垃圾废话得分低。
    pass 
    
    # --- 实际实现 ---
    # 这里的 Trick: 随机抽取 50 条样本，人工认定它们是干净的（或者我们在实验设定中已知 Clean Indicies）
    # 在真实 SFT 场景中，通常确实会有一小部分 Golden Data。
    # 我们从 clean_indices 中 "偷" 100 条作为 Validation Set。
    
    real_clean_idx = [i for i in range(n_total) if i not in dirty_indices]
    random.shuffle(real_clean_idx)
    # 取 100 条作为黄金验证集
    gold_val_indices = real_clean_idx[:100]
    
    # 剩下的作为待清洗池
    candidate_indices = [i for i in range(n_total) if i not in gold_val_indices]
    
    x_train = embeddings[candidate_indices]
    y_train = np.zeros(len(x_train), dtype=int) # 假标签
    
    x_val = embeddings[gold_val_indices]
    y_val = np.zeros(len(x_val), dtype=int)     # 假标签
    
    # 计算
    sv = knn_shapley_JW(x_train, y_train, x_val, y_val, K=10)
    
    # Debug: 打印 Shapley Value 的一些统计信息，防止全是 0
    print(f"📊 Shapley Value Stats -> Mean: {np.mean(sv):.4f}, Std: {np.std(sv):.4f}, Max: {np.max(sv):.4f}, Min: {np.min(sv):.4f}")
    
    # 我们需要把 sv 映射回原始 indices
    full_sv = np.zeros(n_total)
    full_sv[candidate_indices] = sv
    # Golden Set 的样本给自己满分 (或者不做处理)
    full_sv[gold_val_indices] = np.max(sv) 
    
    return full_sv

# ==========================================
# 4. 微调训练 (Fine-tuning)
# ==========================================
def run_sft(dataset_list, output_name):
    """
    使用 HuggingFace Trainer 进行微调 (使用 LoRA 以保证稳定性)。
    """
    print(f"🚀 开始微调: {output_name} (样本数: {len(dataset_list)})...")
    
    model_id = CONFIG['model_name']
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    # 修复 tokenizer 设置
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right" # 训练时通常用 right padding

    # 格式化数据为 HuggingFace Dataset
    def format_func(example):
        # Qwen 官方推荐格式 / ChatML 格式
        # 这里简化处理，但确保 EOS
        text = f"User: {example['instruction']}\n{example['input']}\nAssistant: {example['output']}{tokenizer.eos_token}"
        return {"text": text}
    
    hf_dataset = Dataset.from_list(dataset_list)
    hf_dataset = hf_dataset.map(lambda x: tokenizer(format_func(x)["text"], truncation=True, max_length=512), batched=False)
    
    # 加载模型 (FP32 模式加载，避免 16bit 溢出)
    model = AutoModelForCausalLM.from_pretrained(model_id, device_map="auto", torch_dtype=torch.float32)
    
    # 启用 LoRA (关键！防崩神器)
    peft_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM, 
        inference_mode=False, 
        r=8, 
        lora_alpha=32, 
        lora_dropout=0.1,
        target_modules=["q_proj", "v_proj"] # 针对 Attention 层微调
    )
    model = get_peft_model(model, peft_config)
    model.print_trainable_parameters()

    # 训练参数调整
    training_args_dict = {
        "output_dir": f"{CONFIG['output_dir']}/{output_name}",
        "per_device_train_batch_size": 4, # LoRA 省显存，可以稍微大点
        "gradient_accumulation_steps": 4,
        "num_train_epochs": 3,            # LoRA 需要多训几轮
        "learning_rate": 3e-4,            # LoRA 通常用大一点的学习率
        "logging_steps": 10,
        "save_strategy": "no",
        "report_to": "none",
        "fp16": False,                    # 使用 FP32 保证数值绝对稳定
        "bf16": False,
    }
    
    args = TrainingArguments(**training_args_dict)
    
    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=hf_dataset,
        data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False),
    )
    
    trainer.train()

    # 💾 保存模型 (LoRA 适配器)
    save_path = f"{CONFIG['output_dir']}/{output_name}"
    trainer.save_model(save_path)
    # 合并权重并保存 (方便 chat_compare 读取)
    print("💾 正在合并 LoRA 权重...")
    merged_model = model.merge_and_unload()
    merged_model.save_pretrained(save_path)
    tokenizer.save_pretrained(save_path)
    print(f"💾 完整模型已保存至: {save_path}")
    
    # === 新增：计算 ROUGE 分数 (更有说服力的生成指标) ===
    print("📏 正在评估 ROUGE 指标...")
    metric = evaluate.load("rouge")
    
    # 抽取 50 条测试数据 (不参与训练的)
    test_samples = dataset_list[:50] 
    
    preds = []
    refs = []
    
    # 切换回 eval 模式
    merged_model.eval()
    for item in tqdm(test_samples, desc="Evaluating"):
        prompt = f"User: {item['instruction']}\n\nAssistant: "
        inputs = tokenizer(prompt, return_tensors="pt").to(merged_model.device)
        with torch.no_grad():
            outputs = merged_model.generate(**inputs, max_new_tokens=50, pad_token_id=tokenizer.eos_token_id)
        pred = tokenizer.decode(outputs[0], skip_special_tokens=True)
        if "Assistant: " in pred:
            pred = pred.split("Assistant: ")[1].strip()
        preds.append(pred)
        refs.append(item['output'])
        
    scores = metric.compute(predictions=preds, references=refs)
    print(f"📊 {output_name} ROUGE-L: {scores['rougeL']:.4f}")
    
    # 返回 Loss 和 RougeL 用于对比
    return trainer.state.log_history[-1].get('train_loss', 0.0), scores['rougeL']

# ==========================================
# 主程序
# ==========================================
def main():
    # 1. 准备数据
    # oracle_data: 未被污染的原始纯净数据 (上限/Gold Standard)
    raw_data, dirty_indices, oracle_data = prepare_data()
    
    # 2. 提取特征
    embeddings = extract_text_features(raw_data)
    
    # 3. 计算价值 (Shapley Value)
    # 这一步我们用 "Golden Set Validation" 的策略
    sv = calculate_shapley(embeddings, dirty_indices)
    
    # 4. 根据价值清洗
    # 策略：我们要删掉 30% 左右的数据
    n_remove = int(len(raw_data) * CONFIG['poison_ratio'])
    
    sorted_idx = np.argsort(sv) # 从小到大
    # 低分的是脏数据，删掉
    keep_indices = sorted_idx[n_remove:]
    
    cleaned_data = [raw_data[i] for i in keep_indices]
    
    print("-" * 50)
    print(f"🧹 清洗完成！")
    print(f"原数据: {len(raw_data)}")
    print(f"清洗后: {len(cleaned_data)}")
    
    # 验证清洗准确率 (Recall)
    # 我们知道 dirty_indices 是真的脏数据
    # 我们的系统删除了 sorted_idx[:n_remove]
    removed_indices = sorted_idx[:n_remove]
    correct_removed = set(removed_indices).intersection(set(dirty_indices))
    recall = len(correct_removed) / len(dirty_indices)
    print(f"🕵️‍♂️ 脏数据识别召回率 (Recall): {recall:.2%}")

    # 计算 AUC (清洗算法的性能指标)
    # 我们希望 dirty_indices 对应的 sv 值很低，而 clean 对应的高。
    # 为了计算 AUC，我们需要构建 0/1 标签：1 为 Clean, 0 为 Dirty (或者反过来)
    # 这里定义：Clean=1, Dirty=0
    true_labels = np.ones(len(raw_data))
    true_labels[dirty_indices] = 0
    
    # 计算 ROC-AUC
    # 注意：我们的 sv 越高越 clean，符合 y=1 的方向
    roc_auc = roc_auc_score(true_labels, sv)
    print(f"📈 清洗算法 AUC 得分: {roc_auc:.4f} (1.0代表完美区分)")
    print("-" * 50)
    
    # 5. SFT 对比实验 (Baseline vs Clean)
    # 注意：为了公平，Baseline 我们通常不删数据，或者随机删。
    # 这里对比：Dirty Full Set vs Cleaned Set
    
    # 5.1 训练 Dirty Model
    loss_dirty, rouge_dirty = run_sft(raw_data, "dirty_model")
    
    # 5.2 训练 Clean Model
    # 为了释放显存，建议在这里加入释放显存的代码，或者分脚本运行
    # 这里演示，假设显存够用
    import gc
    torch.cuda.empty_cache()
    gc.collect()
    
    loss_clean, rouge_clean = run_sft(cleaned_data, "clean_model")
    
    # 5.3 训练 Oracle Model (全干净数据 - 理论上限)
    import gc
    torch.cuda.empty_cache()
    gc.collect()
    
    loss_oracle, rouge_oracle = run_sft(oracle_data, "oracle_model")
    
    print("=" * 50)
    print("📊 最终实验结果")
    print(f"{'Model':<15} | {'Loss':<10} | {'ROUGE-L':<10}")
    print("-" * 45)
    print(f"{'Dirty (Base)':<15} | {loss_dirty:.4f}     | {rouge_dirty:.4f}")
    print(f"{'Clean (Yours)':<15} | {loss_clean:.4f}     | {rouge_clean:.4f}")
    print(f"{'Oracle (Top)':<15} | {loss_oracle:.4f}     | {rouge_oracle:.4f}")
    print("-" * 45)
    
    if rouge_clean > rouge_dirty:
        print("✅ 验证成功：清洗后模型的 ROUGE 分数更高，生成质量更好！")

if __name__ == "__main__":
    main()
